version: "3.7"
services:
  kjsencha:
    build:
      args:
        user: kjsencha
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: diva
    container_name: kjsencha-php8
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kjsencha
networks:
  kjsencha:
    driver: bridge